name: Automatización de Script
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: configurando python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Correr script
        run: python script.py

      - name: Commit y Push cambios
        uses: stefanzweifel/git-auto-commit-action@v5
